apiVersion: v1
kind: ServiceAccount
metadata:
  name: coop-web
  namespace: coop-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: coop-web-role
  namespace: coop-app
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: coop-web-rolebinding
  namespace: coop-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: coop-web-role
subjects:
- kind: ServiceAccount
  name: coop-web
  namespace: coop-app
