apiVersion: v1
kind: Service
metadata:
  name: coop-web
  namespace: coop-app
  labels:
    app: coop-web
spec:
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: coop-web
  type: NodePort
  sessionAffinity: ClientIP
